### ISSUE TITLE
Greenbook file + --limit option->last file null

### ISSUE THREAD

**Issue by patricknee** [USPTO/PatentPublicData#11]
Command:

java -cp PatentDocument/target/*:PatentDocument/target/dependency-jars/*:resources gov.uspto.patent.TransformerCli 
--input="/PatentPublicData/BulkDownloader/download/grants/1980/pftaps19800101_wk01.zip" --outBulk=false --outdir="/PatentPublicData/BulkDownloader/download/grants/1980/expanded/" --limit=10

The 10th file will have zero bytes.

Failed logic in the filenumber<filenumberlimit logic. Don't know where yet.

**Comment by bgfeldm** [comment]
Fix has been checked in, fixed by flushing the writer after each write.

**Comment by patricknee** [comment]
Thanks.
