### ISSUE TITLE
Dates question

### ISSUE THREAD

**Issue by patricknee** [USPTO/PatentPublicData#19]
What is the meaning of these date fields?

documentDate
publishedDate
productionDate

I presume documentDate is the day it was granted, publishedDate is when the application became public, but I have no idea on productionDate. 

Is there a difference between grants and applications?

Thank you.

**Comment by bgfeldm** [comment]
Notice: I am not a Patent Examiner nor a Patent Lawyer, and the following is not legal advice; but I will try to be accurate.

    
    publishedDate   (xml field: us-patent-(grant|application)@date-produced)    Date of Publication (Grant or Public Application)
    
    productionDate  (xml field: us-patent-(grant|application)@date-publ)   Date Filed.
        
    documentDate    (xml field: document-id@date)  Usually same as Published Date, as long as current process does not changed to grant ids on the same date as they are made public. 

    
    Difference between applications and grants and reason you likely need both:
        -- not all applications will be granted
        -- not all grants have published applications (applicant can opt out of having their application published; many do and many do not)
        -- Claims are only made public within Grants
        -- The majority of the text should not change, if at all.  Only small spelling and format changes (which do not change meaning) are allow within the application spec (abstract, description, ect..)
        -- Once granted no further applications can take priority to it (believe examiner prior art searches go backwards from the date of the priority application.)  Applicant is notified 3 weeks before granted, given the applicant time to fix errors, file additional applications claiming priority to it, ect..
       -- many years go by before an application is examined and granted

Also as alluded to above Patent Application or Grant can have 2 or 3 associated ids (application id, public application id (if made public), grant id (if granted).  Working with examiners internally they most often use application ids.

**Comment by bgfeldm** [comment]
I have started a FAQ wiki page:

https://github.com/USPTO/PatentPublicData/wiki/FAQ

Feel free to share any additional topics you think should be covered within the FAQ.

**Comment by patricknee** [comment]
Thanks. Very helpful.
