### ISSUE TITLE
Test Failure in PatentAppPubParserTest

### ISSUE THREAD

**Issue by pedagogly** [USPTO/PatentPublicData#23]
I cloned the PatentPublicData repository today, and the build failed because one test failed:

Running gov.uspto.patent.doc.pap.PatentAppPubParserTest
!! This Patent.class method is returning null: 'getDocumentDate()' for Patent id: US20010000943A1
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.314 sec <<< FAILURE!

**Comment by bgfeldm** [comment]
Code has been updated and fixed.
