### ISSUE TITLE
Question: citation patent numbers

### ISSUE THREAD

**Issue by patricknee** [USPTO/PatentPublicData#36]
Brian,

A question: in 2001 the USPTO started publishing the WIPO ST.16 code on patents and "recommended" their use. It looks like additional codes were added in 2011. (https://www.uspto.gov/learning-and-resources/support-centers/electronic-business-center/kind-codes-included-uspto-patent)

In the json documents that are created by TransformerCli, is there referential integrity between the US patent citations in a patent and the other US patents published? That is, if a 2014 patent cites a 1990 patent in the citations collection, is the US patent number in citations[ an item ].text going to match the documentId of the referenced patent?

As an example, I see US7640606B1.json (2010) citation[ num=00001 ].text = "US329663A" (maybe too early for electronic publication) and citation[ num=00015 ].text = "US4391545A" (published 1983).

The ones I have spot checked appear to match. Is the integrity guaranteed?

Thanks,

Patrick

**Comment by bgfeldm** [comment]
Within the published documents the document id has three sub fields: the countrycode, the ID (usually numeric but can start with an "X") and the KindCode.  The three fields are normally joined to create a unique id for the document. 

I asked my wife, whom files patent applications at a law firm. She said they always use the original id as published.  She once cited a patent from from east germany, and filed it as east germany. And if they don't have a kind code she does not add it.

Note for the Greenbook format:
     I map the historic country code to the current country code when possible.  Which is helpful when mapping applications by country, but not when matching id in general, as in citations. I should probably turn this mapping off.
    I also add a kind code, based off the patent type. Which looks to be consistent to what Google Patents does as well as the Master CPC File has the kind code.   Patent number one has kind code of "A".

For the citation format, It has been on my todo all week to ensure they are consistently formatted the same. I hope to get to it soon.

**Comment by bgfeldm** [comment]
I quickly looked at the parsing of Greenbook country codes,  The code only maps historic country codes in addresses.  The original country code should be retained for document ids.

**Comment by patricknee** [comment]
Thanks
