### ISSUE TITLE
NameNode

### ISSUE THREAD

**Issue by patricknee** [USPTO/PatentPublicData#47]
When processing the following 1995 files:

pftaps19951017_wk42.zip
pftaps19950214_wk07.zip

In NameNode.read called from AssigneeName the variable fullName comes up NULL and TransformerCli crashes. 

The current code: 

```
String fullName = nameN != null ? nameN.getText() : null;

List<String> nameParts = Splitter.onPattern("[,;]").limit(2).trimResults().splitToList(fullName);
```

Appears to expect fullName to be null at times, but the com.google.common code called in Splitter.splitToList does not seem to like it. (Is there a version of splitToList that accepts nulls?)

Current workaround I am using is: 

`if (fullName == null) return null;`

**Comment by bgfeldm** [comment]
Your right, and I like your fix. 

Thanks again,

Brian
