### ISSUE TITLE
TransformerCli hanging

### ISSUE THREAD

**Issue by patricknee** [USPTO/PatentPublicData#49]
TransformerCli hanging on ipg120626.zip file, patent US8207315B2.

Have not yet found cause.

Last output line:

`2017-01-25 15:36:04,812 INFO  [       main] US8207315B2          TransformerCli - Record: 'US8207315B2' from /2012/ipg120626.zip:2479`

**Comment by bgfeldm** [comment]
I can confirm the issue.

**Comment by patricknee** [comment]
This patent US8207316B1, downloaded from google, is a 1.7GB pdf and 9,200 pages. It is all text, probably machine generated. The problem with the patent may be just size...
