### ISSUE TITLE
PGPUB stands for Pre-Grant Publication or Application; USPAT stands for U.S Patent.

### ISSUE THREAD

**Issue by aosingh** [USPTO/PatentPublicData#58]
**APPLICATION**

- **AS-IS**
https://github.com/USPTO/PatentPublicData/blob/master/PatentDocument/src/main/java/gov/uspto/patent/model/PatentApplication.java#L22

- **SHOULD-BE**
   ```java
    public PatentApplication(DocumentId documentId, PatentType patentType) {
        super(PatentCorpus.PGPUB, documentId, patentType);
    }
   ```

**GRANT**
- **AS-IS**
https://github.com/USPTO/PatentPublicData/blob/master/PatentDocument/src/main/java/gov/uspto/patent/model/PatentGranted.java#L6

- **SHOULD-BE**
   ```java
   public PatentGranted(DocumentId documentId, PatentType patentType){
		super(PatentCorpus.USPAT, documentId, patentType);
	}
   ```

**Comment by maduraimad** [comment]
Made this change, thanks.
