### ISSUE TITLE
Maven project is not working

### ISSUE THREAD

**Issue by several27** [USPTO/PatentPublicData#62]
None of the dependencies seem to be recognized by IntelliJ and when trying to run from console: `mvn clean install`, maven gives the following error:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.6.0:testCompile (default-testCompile) on project PatentDocument: Compilation failure
[ERROR] /Users/maciej/Developer/FuseMind/PatentPublicData/PatentDocument/src/test/java/gov/uspto/patent/doc/sgml/SgmlTest.java:[35,39] cannot find symbol
[ERROR]   symbol:   method validateGrant(gov.uspto.patent.model.Patent)
[ERROR]   location: class gov.uspto.document.test.ValidatePatent
```

Which makes sense as the class ValidatePatent does not contain method validateGrant method?

**Comment by bgfeldm** [comment]
Eclipse along with Intellij require a few extra steps to convert the project to maven or import the module dependencies.

https://www.jetbrains.com/help/idea/working-with-module-dependencies.html

**Comment by bgfeldm** [comment]
I am not using Intellij, but see if this helps:

https://stackoverflow.com/questions/14450195/how-to-add-maven-modules-to-intellij
