### ISSUE TITLE
Maven build failure

### ISSUE THREAD

**Issue by jamesdhicks** [USPTO/PatentPublicData#69]
I'm having trouble building the project at the command line. `mvn verify` returns the following failure:

    table(gov.uspto.patent.doc.sgml.FormattedTextTest)  Time elapsed: 0.008 sec  <<< FAILURE!
    org.junit.ComparisonFailure: expected:<[<table id="TBL-0001"><colgroup><col width="21pt" align="left" /><col width="196pt" align="left" /></colgroup>

    ]
    <thead><tr><th>head...> but was:<[

    <table id="TBL-0001"><colgroup><col width="21pt" align="left" /><col width="196pt" align="left" /></colgroup>]
    <thead><tr><th>head...>`

Is this a bug?

**Comment by given13** [comment]
Im getting the same bug both in netbeans and eclipse. Help I need to parse the patent data

**Comment by bgfeldm** [comment]
Bug in the Unit Test not the actual code. I will publish fix shortly.

**Comment by given13** [comment]
Hey i could use a big favor.i know this isn't your job *but* i am trying to
search patft for applicant type but i cannot find Any documentation on what
valid entries are for the applicant type field"aaat". I tried to contact
the electronic business center at the uspto phone center but they were
unable to help. The person in the phone said no-one at uspto would know but
i know someone does. I just don't know how to get ahold of them.any help is
greatly appreciated
