### ISSUE TITLE
TRansformerCLI: Do IPC classes need the type Main?

### ISSUE THREAD

**Issue by legolego** [USPTO/PatentPublicData#74]
This is kind of a nitpick, but it doesn't look like IPC classifications have a `main` distinction like CPC classes in the source XML. Can the type field be removed from the JSON?

Is order of IPC classes in the source XML important? Maybe an index number or same order as the source in the JSON files would be better.

[US9428405B2-github.zip](https://github.com/USPTO/PatentPublicData/files/2651763/US9428405B2-github.zip)

Source XML (attached):

`<classifications-ipcr>`
			`<classification-ipcr>`
				`<ipc-version-indicator><date>20060101</date></ipc-version-indicator>`
				`<classification-level>A</classification-level>`
				`<section>F</section>`
				`<class>16</class>`
				`<subclass>K</subclass>`
				`<main-group>17</main-group>`
				`<subgroup>14</subgroup>`
				`<symbol-position>F</symbol-position>`
				`<classification-value>I</classification-value>`
				`<action-date><date>20160830</date></action-date>`
				`<generating-office><country>US</country></generating-office>`
				`<classification-status>B</classification-status>`
				`<classification-data-source>H</classification-data-source>`
			`</classification-ipcr>`

Resulting JSON:

        "ipc": [
            {
                "type": "main",
                "raw": "B01D 17/02",
                "normalized": "B01D 17/02",
                "facets": [
                    "0/B",
                    "1/B/B01",
                    "2/B/B01/B01D",
                    "3/B/B01/B01D/B01D17",
                    "4/B/B01/B01D/B01D17/B01D1702"
                ]
            },

**Comment by bgfeldm** [comment]
The XML schema changed on 2005-08-25.  From 2002 - 2005 the inclosed IPC schema was the same as the current CPC schema.  But I believe the IPC inventive class is equivalent to the CPC main class. I may need to update the output json.
