### ISSUE TITLE
Rows attribute is not working - PEDS Search

### ISSUE THREAD

**Issue by deadlocks** [USPTO/PatentPublicData#90]
The `rows` attribute is not working on `PEDS` using searcher endpoint 

Steps to replicate 
1. Go to https://ped.uspto.gov/api/swagger-ui.html#!/queries/searchDataUsingPOST
2. Paste the following payload [**Working**]

```
{
    "searchText": "applId:(13835121 OR 13836605)",
    "fl": "applId",
    "qf": "applId",
    "facet": "false",
    "start": 0
}
```

3. If we add rows, it will start giving 404 error [**Not Working**]
```
{
    "searchText": "applId:(13835121 OR 13836605)",
    "fl": "applId",
    "qf": "applId",
    "facet": "false",
    "start": 0,
    "rows": 20
}
```

**Comment by bgfeldm** [comment]
This project isn't related to PEDS Search.
